FROM node:12.13.1

RUN mkdir /frontend

COPY frontend/package.json frontend/package-lock.json /.build-deps/
WORKDIR /.build-deps/
RUN npm install
RUN mv /.build-deps/node_modules /frontend/node_modules
RUN rm -r /.build-deps

WORKDIR /frontend
ENTRYPOINT ["npm"]
CMD ["start"]
