FROM python:3.8.1

RUN mkdir /spotify-my-slack

COPY requirements.txt requirements-test.txt /.build-deps/
WORKDIR /.build-deps/
RUN pip install \
    -r requirements.txt \
    -r requirements-test.txt \
    --disable-pip-version-check \
    --no-cache-dir
RUN rm -r /.build-deps

WORKDIR /spotify-my-slack
CMD watchmedo \
    auto-restart \
    --directory=./backend \
    --patterns="*.py" \
    --recursive \
    -- \
    python -m backend.main
