FROM node:10.15.3

RUN mkdir /spotify-my-slack
RUN mkdir /spotify-my-slack/server

COPY server/package.json server/package-lock.json /.build-deps/
WORKDIR /.build-deps/
RUN npm install
RUN mv /.build-deps/node_modules /spotify-my-slack/server/node_modules
RUN rm -r /.build-deps

WORKDIR /spotify-my-slack/server
EXPOSE 5000
ENTRYPOINT ["npm", "run"]
CMD ["watch"]
